### ISSUE TITLE
Create RDF vocabulary for linking a WebID to a wallet

### ISSUE THREAD

**Issue by rubensworks** [KNowledgeOnWebScale/solid-web-monetization#1]
An RDF vocabulary has to be created that allows WebIDs to be linked to one or more wallets.
This vocabulary should be future-proof so that wallets can be annotated with different purposes.
For example, one wallet could be used for work-related matters, while another could be used for personal things.

Possible example:
```
<#me> a <foaf:Person> ;
  pp:hasPaymentPointer [
    a pp:InterledgerPaymentPointer;
    pp:paymentPointerValue "$alice.wallet.example".
  ].
```

Related: https://github.com/interledger/paymentpointers.org/pull/9

**Comment by Falx** [comment]
@rubensworks  Would the following result reflect your intentions with the reification?

![image](https://user-images.githubusercontent.com/1684858/120991269-c123f580-c781-11eb-99ee-8621c69c6ff3.png)

**Comment by rubensworks** [comment]
@Falx Almost; You now have 2 triples, while we need 3 triples:
1. `<#me> pp:hasPaymentPointer _:someBlankNode.`
2. `_:someBlankNode a pp:InterledgerPaymentPointer.`
3. `_:someBlankNode pp:paymentPointerValue "$alice.wallet.example".`

The important thing here is that we use `pp:InterledgerPaymentPointer` as a value to the `rdf:type` predicate (== `a`).
So this means that we mark our blank node resource as something that represents a payment pointer.
