### ISSUE TITLE
Auto-deploy Solid app to configure wallet

### ISSUE THREAD

**Issue by rubensworks** [KNowledgeOnWebScale/solid-web-monetization#3]
Using CI (e.g. GitHub actions), we need to continuously deploy the app somewhere (e.g. GitHub pages for simplicity).

Depends on #2

**Comment by Falx** [comment]
App is now auto-building and deploying on each push on the master branch.
I will close this for now, in the future however we might want to host it on a subpath.

CI deploy URL: https://knowledgeonwebscale.github.io/solid-web-monetization/
